version: '3.1'

services:
  honeypots:
    build:
      context: .
      dockerfile: ./honeypots-Dockerfile
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - postgres
    networks:
      - backend
      - frontend
    ports:
      {temp}

  grafana:
    build: ./grafana
    container_name: grafana
    command: ./import.sh
    ports:
      - '3000:3000'
    links:
      - postgres
    depends_on:
      - honeypots
    networks:
      - backend
      - frontend
    environment:
      GF_SECURITY_ADMIN_USER: changeme457f6460cb287
      GF_SECURITY_ADMIN_PASSWORD: changemed23b8cc6a20e0
    logging:
        driver: none

  postgres:
    image: postgres:9.6
    container_name: chameleon_postgres
    restart: always
    networks:
      - backend
    command: -p 9999
    environment:
      POSTGRES_USER: changeme027a088931d22
      POSTGRES_PASSWORD: changeme0f40773877963
    logging:
        driver: none

networks:
  frontend:
    internal: false
  backend:
    internal: true
